### ISSUE TITLE
Certificate Warning on Discourse

### ISSUE THREAD

**Issue by cogdog** [creativecommons/certificates-themes-plugins#13]
https://discourse.certificates.creativecommons.org/

generates

![cert warning](https://cloud.githubusercontent.com/assets/463038/25019789/b8706474-2040-11e7-816b-f545828cd3f4.jpg)

**Comment by rheaplex** [comment]
Investigating.

**Comment by rheaplex** [comment]
Fixed. Let's Encrypt needed updating in the container.

I've left CloudFlare off for the moment in case that was the problem. We'll have to keep an eye on the load.
