### ISSUE TITLE
Discourse subdomain change possible?

### ISSUE THREAD

**Issue by cogdog** [creativecommons/certificates-themes-plugins#16]
I've not done any changes yet to `discourse.certificates.creativecommons.org` - is it possible w/o too much hassle to run it under `disccuss.certificates.creativecommons.org` it will fit better with how we brand it as a discussion space.

**Comment by rheaplex** [comment]
I can try, I'll have to change the config and the login redirect config.

**Comment by rheaplex** [comment]
In progress. Site will be up and down for an hour.

**Comment by rheaplex** [comment]
Done! The login server is still discoursesso, but that name is descriptive so I think it's OK.
