### ISSUE TITLE
Discourse Image URLs Old URL

### ISSUE THREAD

**Issue by cogdog** [creativecommons/certificates-themes-plugins#17]
Looks like a lot of the images in the content that comes from discourse at http://discuss.certificates.creativecommons.org are broken as pages like:

https://discuss.certificates.creativecommons.org/t/read-me-first-admin-quick-start-guide/10 include references to images at URLs like:

https://discourse.certificates.creativecommons.org/images/emoji/apple/hatching_chick.png?v=3

If it is  more prudent to just wipe and install again, that's fine as I have not yet done anything on the site.

**Comment by rheaplex** [comment]
Hmm I'm hoping I can rebuild it with the handy scripts they provide, I'll take a look.

**Comment by rheaplex** [comment]
The last bit of this fixed it:

https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098

**Comment by cogdog** [comment]
You win the internet today, thanks

**Comment by rheaplex** [comment]
You are welcome. :-)
