### ISSUE TITLE
De-Spam The Site

### ISSUE THREAD

**Issue by rheaplex** [creativecommons/certificates-themes-plugins#3]
I've disabled comments on certificates.cc.org for the moment as the spammers were adding a new comment once every few seconds(!).

I've installed Akismet but it's complaining that my personal subscription, which it's getting via Jetpack, has expired.

@mattl how do we usually handle comment spam in WP?

**Comment by mattl** [comment]
@robmyers Can you make me an admin account plz

**Comment by rheaplex** [comment]
@mattl see email.

**Comment by mattl** [comment]
Okay, the comments I read there now seem legit. I turned off Linkbacks, which are spammy IMO.

**Comment by rheaplex** [comment]
I spammed the couple of hundred spammy ones and turned off comments, which leaves a false impression of the state of things.

I assume you'll be notified of comments/spam now, though.

**Comment by mattl** [comment]
Okay, let's keep an eye on it. Akismet should take care of most of it though.

**Comment by rheaplex** [comment]
Cool. Thank you for setting that up!
