### ISSUE TITLE
SSL Certification Expiration

### ISSUE THREAD

**Issue by cogdog** [creativecommons/certificates-themes-plugins#4]
Got the red scary warnings on https://certificates.creativecommons.org/ 

![cert-expired](https://cloud.githubusercontent.com/assets/463038/17985203/97401808-6ac9-11e6-9fec-d364ebc7c0d6.jpg)

Kind of ironic on a certification site.

**Comment by rheaplex** [comment]
We weren't using the latest Let's Encrypt.

I've installed the latest Let's Encrypt, and run a manual update (future ones will run automatically).

Thank you for reporting this, the server is now much more secure.

**Comment by pgstacey** [comment]
Thanks Rob.
