### ISSUE TITLE
Using CC ID for New Quests Site

### ISSUE THREAD

**Issue by cogdog** [creativecommons/certificates-themes-plugins#6]
For this new site I am building out http://quests.creativecommons.org (not much there now), we anticipate participants creating Wordpress author role accounts to they/we can track their work. Ultimately, we will also add functionality to communicate to Credly's API when they complete a quest.

Is there an advantage/reason for people doing this to create / use CC ID accounts? Security? Will it have an impact if this generates many new accounts? What is your preference Rob from a management standpoint?

**Comment by pgstacey** [comment]
Rob, another related angle on CCID is our plan to roll out the certificates both formally and informally. I've been thinking CCID might be the way we have someone formally "register" indicating their intent to eventually complete and seek "certification". What is the underlying system CCID is build on CAS? Shibboleth? ...?

**Comment by rheaplex** [comment]
CCID is easy to add to WordPress, it's a CAS server and the plugin is simple to install.

Creating a CCID is an extra step for users, but so is creating a WordPress login - if you would like a lower barrier to entry then something like the Social Login plugin would be better.

The number of accounts generated won't affect CCID.

Where CCID might be useful is if you later want people to be able to sign on to another system, or to represent those users on another system.

I have a slight preference for CCID, but see above caveats. :-)

**Comment by cogdog** [comment]
Thanks Rob. The need is more to have a vehicle to connect what they do on this site to credly. I gather we could use whatever they use for authentication. Typically the contributions on the kind of site are done without creating a WP account, but doing so would make it easier to see/show all work.

I'll be digging in more in next weeks. I want to consider CCID if there is value to the org in having more people in there. Luke we could build activities that have them contribute to the wiki??

Thanks

**Comment by rheaplex** [comment]
It's CAS, yes. It's in github as RubyCAS I think.

**Comment by kgodey** [comment]
This seems out of date.
