### ISSUE TITLE
Bad Database Connection

### ISSUE THREAD

**Issue by cogdog** [creativecommons/certificates-themes-plugins#8]
Getting error establishing database connection on https://certificates.creativecommons.org/

**Comment by rheaplex** [comment]
I restarted the webserver. That usually happens when people are trying to brute force the admin site, but this didn't seem to be the case this time.

**Comment by cogdog** [comment]
We are down again. Could this be something I have done on the site?

**Comment by rheaplex** [comment]
We're back. It's almost certainly hacking attempts. I'll take a closer look on Monday.

**Comment by rheaplex** [comment]
The attacks seem to have let up so I'm going to park this for now.
